kind: ServiceAccount
apiVersion: v1
metadata:
  name: regions-updater-service-account
  namespace: pia-webhook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: regions-updater-role
  namespace: pia-webhook-system
rules:
- apiGroups:
  - ""
  resources:
  - "configmaps"
  verbs:
  - "get"
  - "create"
  - "update"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: regions-updater-rolebinding
  namespace: pia-webhook-system
subjects:
  - kind: ServiceAccount
    name: regions-updater-service-account
    namespace: pia-webhook-system
roleRef:
  kind: Role
  name: regions-updater-role
  apiGroup: rbac.authorization.k8s.io